-- GEO Audit — Fact sheets schema (autogeneration + admission control).
-- One row per business per sheet version, its cited claims, and the job queue
-- that decides what gets spent. Run in the PLATFORM project's SQL editor
-- (Supabase Dashboard → SQL Editor). Idempotent: safe on a fresh project or an
-- existing one. Mirrors schema_teasers.sql / schema_site_audit.sql — uuid PKs,
-- RLS enabled with no policies (service_role only; the anon/publishable key
-- cannot read or write these).
--
-- WHICH PROJECT. These tables belong to the PLATFORM project (the one in
-- geoPromptRunner/.env), NOT the website's leads project (the one in
-- geoWebsite/lib/site.ts). They are two different databases. The fact sheet is
-- judged data: it feeds audit_runs.fact_sheet, it is keyed by the same judge
-- cache the runs are, and the spend it authorizes is platform spend. Leads stay
-- where they are; the worker reads them cross-project with the service role and
-- carries `lead_ref` across.
--
-- NO PROSPECT PII CROSSES OVER. `lead_ref` is the leads row id and nothing
-- else — no email, no phone. The report still gets emailed from the queue that
-- already holds the address. Copying it here would put prospect contact details
-- in a second project for no operational gain.
--
-- WHY A TABLE AND NOT A STORAGE BUCKET. The sheet is queried, not just fetched:
-- "does this domain already have one", "what changed between versions", "which
-- claims are still public_source_only". A bucket answers none of those without
-- listing files and parsing markdown. The bucket's job is the raw page
-- snapshots that back each verbatim_quote (see §Sources at the bottom).

-- ---------------------------------------------------------------------------
-- fact_sheets — one row per business per version.
-- ---------------------------------------------------------------------------
create table if not exists public.fact_sheets (
    id uuid primary key default gen_random_uuid(),
    -- Registrable domain, already normalized by src/audit/offsite/tools.py
    -- _registered_domain(). The DB only enforces that it arrived lowercase and
    -- bare: proper PSL normalization needs Python, so this is a guard against a
    -- careless writer, not the normalizer itself.
    domain text not null
        check (domain = lower(domain) and domain !~ '^https?://' and domain !~ '/'),
    business_name text,
    business_kind text not null default 'local_service'
        check (business_kind in ('product', 'local_service')),
    -- The leads row this originated from (other project's uuid, as text).
    -- Nullable: a sheet can be generated by hand for a client who never
    -- submitted the form.
    lead_ref text,
    version int not null default 1 check (version >= 1),
    -- Renderer 2 output (the markdown sheet). Renderer 1 (CSV fact rows) is
    -- derived from fact_claims at build time and deliberately NOT stored — two
    -- stored representations of the same facts is how they drift.
    rendered_md text,
    verification_tier text not null default 'public_source_only'
        check (verification_tier in
            ('public_source_only', 'cross_confirmed', 'client_confirmed')),
    -- draft: generated, not reviewed. active: the sheet a run may use.
    -- superseded: an older version, kept for diffing.
    -- 'rejected' is a REVIEWED state, not a deleted one (F4). A reviewer saying
    -- "this sheet is wrong" is information: it means the extractor produced
    -- something plausible-but-false on this domain, which is the signal that
    -- tunes L1. Deleting the row would throw that away and leave the next
    -- regeneration to make the same mistake with nobody the wiser.
    state text not null default 'draft'
        check (state in ('draft', 'active', 'superseded', 'rejected')),
    -- Why a reviewer rejected it. NULL for every other state, and NULL rather
    -- than '' for a rejection with no note, so "rejected without a reason" stays
    -- distinguishable from "the reason failed to persist" (the /teasers
    -- convention).
    reject_reason text,
    -- Open questions the generator could not resolve — the §4.3 disagreements
    -- and the un-derivable negatives. This is Josh's call list, and it is the
    -- most valuable column here for the first ten clients.
    questions jsonb not null default '[]'::jsonb,
    -- Storage prefix for the gzipped page snapshots backing the quotes.
    source_snapshot_prefix text,
    generated_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (domain, version)
);

-- ONE ACTIVE SHEET PER BUSINESS. This is the constraint that means "the same
-- company cannot be stored twice": a second generation for a domain that
-- already has an active sheet must either supersede it (bump version, demote
-- the old row) or be refused. Versions are retained on purpose — a sheet is a
-- measurement reference, and §6 of the plan needs two versions present to diff
-- what a regeneration changed.
create unique index if not exists uq_fact_sheets_active_domain
    on public.fact_sheets (domain) where state = 'active';

create index if not exists idx_fact_sheets_domain on public.fact_sheets (domain);
create index if not exists idx_fact_sheets_state on public.fact_sheets (state);

-- ---------------------------------------------------------------------------
-- fact_claims — the typed claims (plan §2). One row per FactClaim.
-- ---------------------------------------------------------------------------
create table if not exists public.fact_claims (
    id uuid primary key default gen_random_uuid(),
    fact_sheet_id uuid not null references public.fact_sheets (id) on delete cascade,
    claim_id text not null,                       -- "FS-01", stable across versions
    section text not null
        check (section in ('identity', 'contact', 'hours', 'service_area',
                           'licensing', 'services_pricing', 'presence')),
    key text not null,                            -- the fact-row key: "hours_sunday"
    value text not null,                          -- a complete assertion (plan §4.4)
    polarity text not null default 'positive'
        check (polarity in ('positive', 'negative')),
    -- The literal source line. NOT a paraphrase. A row whose quote is not a
    -- substring of the snapshot at source_url never should have been written —
    -- the gate lives in the generator (plan §4.1), because SQL cannot check it.
    verbatim_quote text not null,
    source_url text not null,
    source_kind text not null
        check (source_kind in ('site_jsonld', 'site_text', 'gbp', 'directory',
                               'registry', 'lead_form', 'client')),
    as_of date not null,
    verification text not null default 'public_source_only'
        check (verification in
            ('public_source_only', 'cross_confirmed', 'client_confirmed')),
    confidence text not null default 'medium'
        check (confidence in ('high', 'medium', 'low')),
    created_at timestamptz not null default now(),
    unique (fact_sheet_id, claim_id)
);

create index if not exists idx_fact_claims_sheet on public.fact_claims (fact_sheet_id);
create index if not exists idx_fact_claims_section on public.fact_claims (section);

-- THE SECTION LIST ABOVE IS LOCAL-SHAPED, and the product branch of the intake
-- appended three more members to `SheetSection` (src/audit/factsheet/models.py)
-- without widening this constraint: `features`, `positioning`, `watchlist`.
--
-- WHAT THAT COST. `save_fact_sheet` inserts the sheet row and then upserts ALL
-- of its claims in ONE statement. A product sheet carries features_* and
-- positioning_* claims, so that upsert hit `fact_claims_section_check` (23514)
-- and rolled back as a batch — leaving the `fact_sheets` row present, its
-- `rendered_md` complete, and ZERO claim rows. The review screen renders from
-- the claims, so a sheet that generated perfectly displayed as empty and read
-- as data loss. blackpropeller.com v1/v2 is exactly this.
--
-- AN ALTER RATHER THAN AN EDIT TO THE `create` ABOVE, for the same reason
-- schema_factsheet_intake.sql alters in its `crawl_state` column: an existing
-- project has to pick this up without being dropped. Drop-then-add rather than
-- `if not exists`, because Postgres has no way to widen a check in place.
--
-- Widening only. Every value the old constraint accepted, this one accepts.
alter table public.fact_claims
    drop constraint if exists fact_claims_section_check;
alter table public.fact_claims
    add constraint fact_claims_section_check
    check (section in ('identity', 'contact', 'hours', 'service_area',
                       'licensing', 'services_pricing', 'presence',
                       'features', 'positioning', 'watchlist'));

-- ---------------------------------------------------------------------------
-- factsheet_jobs — the queue, and where the limiter actually lives.
-- ---------------------------------------------------------------------------
-- Tier 1 is deterministic extraction (a fetch and a parse; effectively free).
-- Tier 2 is the LLM/agent layers and is the only thing that costs money, so the
-- caps below apply to tier 2. A skipped job is RECORDED, never dropped: the
-- lead-alert work learned that a silent failure is worse than no channel,
-- because you stop checking.
create table if not exists public.factsheet_jobs (
    id uuid primary key default gen_random_uuid(),
    domain text not null check (domain = lower(domain)),
    lead_ref text,
    tier smallint not null default 1 check (tier in (1, 2)),
    state text not null default 'queued'
        check (state in ('queued', 'running', 'done', 'failed',
                         'skipped_duplicate',  -- domain already has a fresh sheet
                         'skipped_cap',        -- daily tier-2 budget spent
                         'skipped_unusable')), -- site thin / challenge / dead
    attempts int not null default 0,
    fact_sheet_id uuid references public.fact_sheets (id) on delete set null,
    cost_usd numeric(10, 4) not null default 0,
    error text,
    claimed_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null default now()
);

-- ONE IN-FLIGHT JOB PER DOMAIN, enforced by Postgres rather than by the worker.
-- Two leads from the same business arriving in the same minute is the ordinary
-- case (an owner submits twice), and an app-level check loses that race.
create unique index if not exists uq_factsheet_jobs_inflight
    on public.factsheet_jobs (domain) where state in ('queued', 'running');

create index if not exists idx_factsheet_jobs_state on public.factsheet_jobs (state);
create index if not exists idx_factsheet_jobs_created on public.factsheet_jobs (created_at desc);

-- The daily tier-2 budget, read by the worker before it claims. Mirrors the
-- hourly cap on lead alerts: past the cap, jobs record as skipped_cap.
create or replace view public.factsheet_spend_today as
select
    count(*) filter (where tier = 2 and state in ('running', 'done')) as tier2_runs,
    coalesce(sum(cost_usd), 0)                                        as spend_usd
from public.factsheet_jobs
where created_at > now() - interval '24 hours';

-- ---------------------------------------------------------------------------
-- Access. Same posture as schema_teasers.sql: RLS on, NO policies, so only the
-- service_role (which bypasses RLS) can touch these. The explicit revokes are
-- belt-and-braces against Supabase's stock pg_default_acl, which grants ALL to
-- anon and authenticated on every new object created by `postgres` in public —
-- the footgun documented in geoWebsite/scaffold.md §6a. A new table is exposed
-- by default and safe only by RLS accident; do not rely on the accident.
-- ---------------------------------------------------------------------------
alter table public.fact_sheets enable row level security;
alter table public.fact_claims enable row level security;
alter table public.factsheet_jobs enable row level security;

revoke all on public.fact_sheets from anon, authenticated;
revoke all on public.fact_claims from anon, authenticated;
revoke all on public.factsheet_jobs from anon, authenticated;
revoke all on public.factsheet_spend_today from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Sources bucket (create in Dashboard → Storage, PRIVATE).
--
--   Name:  factsheet-sources
--   Paths: <domain>/v<version>/<sha256-of-url>.html.gz
--
-- Same shape as the existing `site-audit-html` bucket, so db.py's gzip
-- upload/download helpers apply unchanged. This is what makes the verbatim
-- quote gate auditable six months later, when the page has been redesigned and
-- the claim is the only thing anyone can still check.
--
-- Storage is create-only, per the platform's invariant: the only delete path is
-- explicit project deletion, which removes Storage blobs before rows.
-- ---------------------------------------------------------------------------
